"""Centralized selectors for goofish.com.

All selectors in this file must be confirmed against a real logged-in
headed browser session before enabling real operations. Do not guess
or scatter selectors across automation code.
"""


GOOFISH_URLS = {
    "home": "https://www.goofish.com/",
    "messages": "https://www.goofish.com/im",
    "search": "https://www.goofish.com/search?q={keyword}",
    "seller_listings": "https://www.goofish.com/personal",
}


GOOFISH_SELECTORS = {
    # TODO: Confirm after manual login. Prefer role/text/data attributes where
    # available. Avoid brittle class names generated by frontend builds.
    "login_indicator": None,
    "captcha_or_slider": None,
    "message_thread": None,
    "message_text": None,
    "reply_textarea": None,
    "reply_send_button": None,
    "search_input": None,
    # Confirmed on 2026-06-20 from the real Goofish search page
    # https://www.goofish.com/search?q=%E9%94%AE%E7%9B%98
    "search_result_card": "a.feeds-item-wrap--rGdH_KoF",
    "result_title": ".row1-wrap-title--qIlOySTh",
    "result_price": ".row3-wrap-price--IZmX7M0K .price-wrap--YzmU5cUl",
    "result_sold_count": ".row3-wrap-price--IZmX7M0K .text--MaM9Cmdn",
    # Confirmed on 2026-06-20 after login on the real personal page.
    "seller_personal_entry": 'a[href*="/personal"]',
    "seller_management_button": 'text="宝贝管理"',
    "seller_on_sale_tab": 'text="在售"',
    "seller_empty_state": '.feeds-list-empty--CZPXhSgW:has-text("暂无商品")',
    # Not enabled until a real on-sale item card exists on this account.
    "seller_listing_card": None,
    "seller_listing_title": None,
    "seller_listing_price": None,
    "seller_listing_stats": None,
    "seller_listing_published_at": None,
    "seller_listing_link": None,
}
